/**
 * 错误码常量定义
 */
export const ERROR_CODES = {
  // 配置错误
  CONFIG_FILE_NOT_FOUND: 'CONFIG_FILE_NOT_FOUND',
  CONFIG_INVALID_FORMAT: 'CONFIG_INVALID_FORMAT',
  CONFIG_MISSING_FIELD: 'CONFIG_MISSING_FIELD',

  // 网络错误
  NETWORK_CONNECTION_FAILED: 'NETWORK_CONNECTION_FAILED',
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  NETWORK_UNREACHABLE: 'NETWORK_UNREACHABLE',

  // Apifox API 错误
  APIFOX_API_AUTH_FAILED: 'APIFOX_API_AUTH_FAILED',
  APIFOX_API_PERMISSION_DENIED: 'APIFOX_API_PERMISSION_DENIED',
  APIFOX_API_REQUEST_FAILED: 'APIFOX_API_REQUEST_FAILED',

  // 验证错误
  VALIDATION_PARAM_MISSING: 'VALIDATION_PARAM_MISSING',
  VALIDATION_PARAM_TYPE_ERROR: 'VALIDATION_PARAM_TYPE_ERROR',
  VALIDATION_SCHEMA_ERROR: 'VALIDATION_SCHEMA_ERROR',
} as const;

/**
 * 错误码到 HTTP 状态码的映射
 */
export const ERROR_TO_HTTP_STATUS: Record<string, number> = {
  CONFIG_ERROR: 500,
  NETWORK_ERROR: 502,
  APIFOX_API_ERROR: 502,
  VALIDATION_ERROR: 400,
};

